conda install -y -c psi4 gcc-5
conda install -y -c anaconda cmake
conda install -y -c anaconda libstdcxx-ng
conda install -y -c anaconda pyaudio
conda install -y -c conda-forge libsndfile
conda install -y -c conda-forge ffmpeg
conda install -y -c conda-forge libsndfile
conda install -y -c conda-forge boost
conda install -y -c conda-forge openblas
conda install -y -c conda-forge fftw
conda install -y -c conda-forge gflags
conda install -y -c conda-forge glog
conda install -y -c conda-forge mkl
conda install -y -c conda-forge cub
conda install -y -c conda-forge pybind11
conda install -y -c conda-forge librosa
conda install -y -c conda-forge pydub
conda install -y -c omnia eigen3
